name: Scraper Run

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # 🔥 THIS IS THE REAL FIX
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add matches.json
          git commit -m "auto update" || echo "no changes"
          git push
